#zsh
set-option -g default-shell /bin/zsh
# tmux 256
set-option -g default-terminal screen-256color
set -g terminal-overrides 'xterm:colors=256'

unbind C-b
set -g prefix C-t
bind -T copy-mode-vi v send -X begin-selection

set-option -g repeat-time 0
#reload settings
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# | split wihdow horiontal
bind | split-window -h

# - split window vertical
bind - split-window -v

set-window-option -g mode-keys vi
# vim like pane switching
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
#vim like pane resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

set-option -g status-interval 1
set-option -g status-position top
set-option -g status-left-length 50
set-option -g status-right-length 50
# status-left
set-option -g status-left "[#H][#S][#W] "
# status-righ
set-option -g status-right "[%Y-%m-%d][%a][%H:%M]"
# status color
set -g status-fg black
set -g status-bg green
